_prefs: 
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -116.9749
  - 51.2895
  - 13
description: 'This is a vector overlay for Golden Cycling Club.  '
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: gcc-overlay
source: "tmsource://c:/Users/spencer/Documents/GitHub/gcc-mapbox/sources/gcc-source.tm2source"
styles: 
  - trails.mss
  - annotation.mss
  - extra.mss
template: ''
